import { beforeEach, describe, expect, it, vi } from 'vitest'

const invokeMock = vi.fn()

vi.mock('@tauri-apps/api/core', () => ({
  invoke: (...args: unknown[]) => invokeMock(...args),
}))

describe('central skill tools', () => {
  beforeEach(() => {
    invokeMock.mockReset()
  })

  it('registers model-created skills in the app database instead of the workspace', async () => {
    const { getAllTools, registerAllBuiltinTools } = await import('./registry')
    registerAllBuiltinTools()
    const tool = getAllTools().find((entry) => entry.name === 'SaveSkill')!
    invokeMock.mockResolvedValue(undefined)

    const result = await tool.call({
      name: 'Project Summary',
      description: 'Summarizes a project consistently.',
      prompt_template: 'Summarize this project:\n{{input}}',
      trigger_pattern: 'summarize project',
      run_mode: 'execute',
    }, { cwd: 'C:/workspace' } as never)

    expect(invokeMock).toHaveBeenCalledWith('skill_upsert', expect.objectContaining({
      name: 'Project Summary',
      promptTemplate: 'Summarize this project:\n{{input}}',
      autoGenerated: true,
    }))
    expect(String(result.data)).toContain('central LocalAI Cowork skill store')
    expect(invokeMock).not.toHaveBeenCalledWith(expect.stringMatching(/^fs_/), expect.anything())
  })

  it('loads and renders a registered skill before running it', async () => {
    const { getAllTools, registerAllBuiltinTools } = await import('./registry')
    registerAllBuiltinTools()
    const tool = getAllTools().find((entry) => entry.name === 'Skill')!
    invokeMock.mockResolvedValue([{
      name: 'Project Summary',
      prompt_template: 'Summarize:\n{{input}}',
      run_mode: 'execute',
    }])

    const result = await tool.call({
      skill_name: 'project summary',
      input: 'Alpha repository',
    }, { cwd: 'C:/workspace' } as never)

    expect(invokeMock).toHaveBeenCalledWith('skill_list', { limit: 200 })
    expect(String(result.data)).toContain('Summarize:\nAlpha repository')
  })
})
