import { create } from 'zustand'
import { safeInvoke } from '../utils/safeInvoke'

export type Skill = {
  id: string
  name: string
  description: string
  prompt_template: string
  trigger_pattern: string | null
  run_mode: string
  version: number
  usage_count: number
  success_count: number
  fail_count: number
  avg_quality: number
  auto_generated: boolean
  parent_skill_id: string | null
  source_task_ids: string | null
  created_at: string
  updated_at: string
}

export type SkillAutoGenResult = {
  generated: boolean
  skill_name: string | null
  reason: string
}

export type LearningOutcome = {
  id: string
  run_id: string | null
  thread_id: string | null
  task_id: string | null
  outcome_type: string
  description: string
  learned_pattern: string | null
  confidence: number
  applied_count: number
  created_at: string
}

/* ── Local fallback storage ─────────────────────────────────────────── */

const LOCAL_SKILLS_KEY = 'open-cowork-skills'
const LOCAL_LEARNINGS_KEY = 'open-cowork-learnings'

function getLocalSkills(): Skill[] {
  try { return JSON.parse(localStorage.getItem(LOCAL_SKILLS_KEY) ?? '[]') } catch { return [] }
}
function setLocalSkills(skills: Skill[]): void {
  try { localStorage.setItem(LOCAL_SKILLS_KEY, JSON.stringify(skills)) } catch { /* noop */ }
}
function getLocalLearnings(): LearningOutcome[] {
  try { return JSON.parse(localStorage.getItem(LOCAL_LEARNINGS_KEY) ?? '[]') } catch { return [] }
}
function setLocalLearnings(learnings: LearningOutcome[]): void {
  try { localStorage.setItem(LOCAL_LEARNINGS_KEY, JSON.stringify(learnings)) } catch { /* noop */ }
}

function mirrorSkillToDaemon(skill: {
  id: string
  name: string
  description: string
  promptTemplate: string
  triggerPattern?: string
  runMode?: string
  autoGenerated?: boolean
  parentSkillId?: string
  sourceTaskIds?: string
}): void {
  void import('../runtime/localDaemonEntities')
    .then(({ mirrorDurableLocalEntity }) => mirrorDurableLocalEntity('skill', skill.id, {
      name: skill.name,
      description: skill.description,
      prompt_template: skill.promptTemplate,
      trigger_pattern: skill.triggerPattern ?? null,
      run_mode: skill.runMode ?? 'execute',
      auto_generated: skill.autoGenerated ?? false,
      parent_skill_id: skill.parentSkillId ?? null,
      source_task_ids: skill.sourceTaskIds ?? null,
      source: 'desktop',
    }))
    .catch((error) => console.warn('[skillStore] Daemon skill mirror failed', error))
}

function tombstoneSkillInDaemon(id: string): void {
  void import('../runtime/localDaemonEntities')
    .then(({ tombstoneDurableLocalEntity }) => tombstoneDurableLocalEntity('skill', id))
    .catch((error) => console.warn('[skillStore] Daemon skill delete failed', error))
}

/* ── Store ────────────────────────────────────────────────────────────── */

type SkillState = {
  skills: Skill[]
  learnings: LearningOutcome[]
  loading: boolean
  error: string | null

  loadSkills: (limit?: number) => Promise<void>
  upsertSkill: (s: {
    id: string; name: string; description: string; promptTemplate: string
    triggerPattern?: string; runMode?: string; autoGenerated?: boolean
    parentSkillId?: string; sourceTaskIds?: string
  }) => Promise<void>
  deleteSkill: (id: string) => Promise<void>
  recordUsage: (skillId: string, success: boolean, quality: number) => Promise<void>
  improveSkill: (skillId: string, newPromptTemplate: string, reason: string) => Promise<void>
  matchSkill: (input: string) => Promise<Skill | null>
  autoGenerate: (taskTitle: string, taskPrompt: string, taskStepsSummary: string, taskOutcome: string) => Promise<SkillAutoGenResult>

  loadLearnings: (limit?: number) => Promise<void>
  addLearning: (l: {
    runId?: string; threadId?: string; taskId?: string; outcomeType: string; description: string
    learnedPattern?: string; confidence?: number
  }) => Promise<void>
}

export const useSkillStore = create<SkillState>()((set) => ({
  skills: [],
  learnings: [],
  loading: false,
  error: null,

  loadSkills: async (limit = 200) => {
    set({ loading: true, error: null })
    try {
      const skills = await safeInvoke<Skill[]>('skill_list', { limit }, getLocalSkills())
      set({ skills, loading: false })
    } catch (e) {
      set({ error: String(e), loading: false })
    }
  },

  upsertSkill: async (s) => {
    try {
      await safeInvoke('skill_upsert', {
        id: s.id,
        name: s.name,
        description: s.description,
        promptTemplate: s.promptTemplate,
        triggerPattern: s.triggerPattern ?? null,
        runMode: s.runMode ?? 'execute',
        autoGenerated: s.autoGenerated ?? false,
        parentSkillId: s.parentSkillId ?? null,
        sourceTaskIds: s.sourceTaskIds ?? null,
      }, undefined)
    } catch {
      // Fallback: save locally
      const now = new Date().toISOString()
      const local = getLocalSkills()
      const full: Skill = {
        id: s.id, name: s.name, description: s.description,
        prompt_template: s.promptTemplate, trigger_pattern: s.triggerPattern ?? null,
        run_mode: s.runMode ?? 'execute', version: 1, usage_count: 0,
        success_count: 0, fail_count: 0, avg_quality: 0,
        auto_generated: s.autoGenerated ?? false,
        parent_skill_id: s.parentSkillId ?? null,
        source_task_ids: s.sourceTaskIds ?? null,
        created_at: now, updated_at: now,
      }
      const idx = local.findIndex(x => x.id === s.id)
      if (idx >= 0) local[idx] = full; else local.unshift(full)
      setLocalSkills(local)
    }
    mirrorSkillToDaemon(s)
  },

  deleteSkill: async (id) => {
    try {
      await safeInvoke('skill_delete', { id }, undefined)
      set((s) => ({ skills: s.skills.filter((sk) => sk.id !== id) }))
    } catch {
      const local = getLocalSkills().filter(sk => sk.id !== id)
      setLocalSkills(local)
      set((s) => ({ skills: s.skills.filter((sk) => sk.id !== id) }))
    }
    tombstoneSkillInDaemon(id)
  },

  recordUsage: async (skillId, success, quality) => {
    try {
      await safeInvoke('skill_record_usage', { id: skillId, success, quality }, undefined)
    } catch {
      // Update local skill stats
      const local = getLocalSkills()
      const idx = local.findIndex(s => s.id === skillId)
      if (idx >= 0) {
        local[idx].usage_count++
        if (success) local[idx].success_count++
        else local[idx].fail_count++
        setLocalSkills(local)
      }
    }
  },

  improveSkill: async (skillId, newPromptTemplate, reason) => {
    try {
      await safeInvoke('skill_improve', { skillId, newPromptTemplate, reason }, undefined)
    } catch {
      const local = getLocalSkills()
      const idx = local.findIndex(s => s.id === skillId)
      if (idx >= 0) {
        local[idx].prompt_template = newPromptTemplate
        local[idx].version++
        local[idx].updated_at = new Date().toISOString()
        setLocalSkills(local)
      }
    }
  },

  matchSkill: async (input) => {
    try {
      return await safeInvoke<Skill | null>('skill_match', { userInput: input }, null)
    } catch {
      // Fallback: simple pattern matching
      const local = getLocalSkills()
      const lower = input.toLowerCase()
      return local.find(s =>
        s.trigger_pattern && lower.includes(s.trigger_pattern.toLowerCase())
      ) ?? null
    }
  },

  autoGenerate: async (taskTitle, taskPrompt, taskStepsSummary, taskOutcome) => {
    try {
      return await safeInvoke<SkillAutoGenResult>('skill_auto_generate', {
        taskTitle, taskPrompt, taskStepsSummary, taskOutcome,
      }, { generated: false, skill_name: null, reason: 'Auto-Generierung nur in Desktop-App available.' })
    } catch {
      return { generated: false, skill_name: null, reason: 'Skill-Auto-Generierung failed.' }
    }
  },

  loadLearnings: async (limit = 100) => {
    set({ loading: true })
    try {
      const learnings = await safeInvoke<LearningOutcome[]>('learning_list', { limit }, getLocalLearnings())
      set({ learnings, loading: false })
    } catch (e) {
      set({ error: String(e), loading: false })
    }
  },

  addLearning: async (l) => {
    const id = `learn-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`
    try {
      await safeInvoke('learning_upsert', {
        id,
        runId: l.runId ?? null,
        threadId: l.threadId ?? null,
        taskId: l.taskId ?? null,
        outcomeType: l.outcomeType,
        description: l.description,
        learnedPattern: l.learnedPattern ?? null,
        confidence: l.confidence ?? 1.0,
      }, undefined)
    } catch {
      // Fallback: save locally
      const local = getLocalLearnings()
      local.unshift({
        id,
        run_id: l.runId ?? null,
        thread_id: l.threadId ?? null,
        task_id: l.taskId ?? null,
        outcome_type: l.outcomeType,
        description: l.description,
        learned_pattern: l.learnedPattern ?? null,
        confidence: l.confidence ?? 1.0,
        applied_count: 0,
        created_at: new Date().toISOString(),
      })
      setLocalLearnings(local.slice(0, 200))
    }
  },
}))
