import { z } from 'zod'

import {
  MIN_COMPATIBLE_SCHEMA_VERSION,
  SCHEMA_VERSION,
  approvalRequestSchema,
  applyProjectVersionRequestSchema,
  authSessionRecordSchema,
  capabilityCatalogSchema,
  capabilityDescriptorSchema,
  capabilitySchema,
  createProjectVersionRequestSchema,
  desktopSessionSchema,
  desktopStreamTicketSchema,
  executorKindSchema,
  executorRecordSchema,
  executorRegistrationSchema,
  executorTargetSchema,
  invitationSecretSchema,
  mergeReviewQuerySchema,
  listRunsResponseSchema,
  messageRecordSchema,
  messageRoleSchema,
  operationsSnapshotSchema,
  passkeyChallengeSchema,
  passkeyRecordSchema,
  projectPrivacySchema,
  projectMergeReviewSchema,
  projectRecordSchema,
  projectVersionSchema,
  mergeFileReviewSchema,
  mergeFileStatusSchema,
  mergeResolutionChoiceSchema,
  mergeFileResolutionSchema,
  applyProjectMergeRequestSchema,
  providerProfileSchema,
  pullSyncChangesResponseSchema,
  pushSyncChangesResponseSchema,
  pushConfigurationSchema,
  pushSubscriptionRecordSchema,
  quotaLimitsRecordSchema,
  quotaScopeTypeSchema,
  quotaStatusSchema,
  quotaUsageRecordSchema,
  reauthenticationGrantSchema,
  runArtifactSchema,
  runEventSchema,
  runInputRequestSchema,
  runRecordSchema,
  runSpecSchema,
  runStateSchema,
  scheduleRecordSchema,
  serverSyncChangeSchema,
  syncApplyResultSchema,
  syncChangeSchema,
  syncOperationSchema,
  syncedEntitySchema,
  syncedEntityPageSchema,
  supportGrantRecordSchema,
  teamRecordSchema,
  teamMemberRecordSchema,
  teamRoleSchema,
  taskDefinitionSchema,
  terminalSessionTicketSchema,
  threadRecordSchema,
  threadMessageRunSchema,
  totpRecoveryCodesSchema,
  totpSetupSchema,
  totpStatusSchema,
  versionResponseSchema,
  updateProjectRequestSchema,
  updateThreadRequestSchema,
} from './contracts'

export const protocolSchemaVersion = SCHEMA_VERSION
export const minimumCompatibleSchemaVersion = MIN_COMPATIBLE_SCHEMA_VERSION

const uuid = z.string().uuid()
const timestamp = z.string().datetime({ offset: true })
const revision = z.number().int().positive()
const jsonValue = z.unknown()

export const executorPoolSchema = z.object({
  schema_version: z.number().int().positive(), id: uuid, revision, etag: z.string(),
  name: z.string(), kind: executorKindSchema, team_id: uuid.nullable(), policy: jsonValue,
  deleted_at: timestamp.nullable(),
})

export const snapshotChunkSchema = z.object({
  digest: z.string().regex(/^[0-9a-f]{64}$/), plaintext_size: z.number().int().nonnegative(),
  ciphertext_size: z.number().int().nonnegative(),
})
export const snapshotFileSchema = z.object({
  path: z.string(), size: z.number().int().nonnegative(), mode: z.number().int().nonnegative(),
  modified_at: timestamp, chunks: z.array(snapshotChunkSchema),
})
export const snapshotManifestSchema = z.object({
  schema_version: z.number().int().positive(), id: uuid, project_id: uuid,
  total_bytes: z.number().int().nonnegative(), files: z.array(snapshotFileSchema),
  encryption_key_id: z.string(), created_at: timestamp, expires_at: timestamp.nullable(),
})
export const snapshotUploadSessionSchema = z.object({
  schema_version: z.number().int().positive(), manifest_id: uuid,
  missing_chunks: z.array(z.string().regex(/^[0-9a-f]{64}$/)),
  max_chunk_bytes: z.number().int().positive(), expires_at: timestamp.nullable(),
  warnings: z.array(z.string()),
})
export const snapshotChunkReceiptSchema = z.object({
  schema_version: z.number().int().positive(), manifest_id: uuid,
  digest: z.string().regex(/^[0-9a-f]{64}$/), plaintext_size: z.number().int().nonnegative(),
  ciphertext_size: z.number().int().nonnegative(), deduplicated: z.boolean(),
  warnings: z.array(z.string()),
})
export const runCheckpointSchema = z.object({
  schema_version: z.number().int().positive(), id: uuid, run_id: uuid,
  sequence: z.number().int().nonnegative(), safe_to_resume: z.boolean(),
  executor_state: jsonValue, created_at: timestamp,
})

export const contractSchemaRegistry = {
  ApprovalRequest: approvalRequestSchema,
  ApplyProjectVersionRequest: applyProjectVersionRequestSchema,
  AuthSessionRecord: authSessionRecordSchema,
  Capability: capabilitySchema,
  CapabilityCatalog: capabilityCatalogSchema,
  CapabilityDescriptor: capabilityDescriptorSchema,
  CreateProjectVersionRequest: createProjectVersionRequestSchema,
  DesktopSession: desktopSessionSchema,
  DesktopStreamTicket: desktopStreamTicketSchema,
  ExecutorPool: executorPoolSchema,
  ExecutorRecord: executorRecordSchema,
  ExecutorRegistration: executorRegistrationSchema,
  ExecutorTarget: executorTargetSchema,
  InvitationSecret: invitationSecretSchema,
  ListRunsResponse: listRunsResponseSchema,
  MessageRecord: messageRecordSchema,
  MessageRole: messageRoleSchema,
  OperationsSnapshot: operationsSnapshotSchema,
  PasskeyChallenge: passkeyChallengeSchema,
  PasskeyRecord: passkeyRecordSchema,
  ApplyProjectMergeRequest: applyProjectMergeRequestSchema,
  MergeFileResolution: mergeFileResolutionSchema,
  MergeFileReview: mergeFileReviewSchema,
  MergeFileStatus: mergeFileStatusSchema,
  MergeResolutionChoice: mergeResolutionChoiceSchema,
  MergeReviewQuery: mergeReviewQuerySchema,
  ProjectMergeReview: projectMergeReviewSchema,
  ProjectPrivacy: projectPrivacySchema,
  ProjectRecord: projectRecordSchema,
  ProviderProfile: providerProfileSchema,
  ProjectVersion: projectVersionSchema,
  PullSyncChangesResponse: pullSyncChangesResponseSchema,
  PushSyncChangesResponse: pushSyncChangesResponseSchema,
  PushConfiguration: pushConfigurationSchema,
  PushSubscriptionRecord: pushSubscriptionRecordSchema,
  QuotaLimitsRecord: quotaLimitsRecordSchema,
  QuotaScopeType: quotaScopeTypeSchema,
  QuotaStatus: quotaStatusSchema,
  QuotaUsageRecord: quotaUsageRecordSchema,
  ReauthenticationGrant: reauthenticationGrantSchema,
  RunArtifact: runArtifactSchema,
  RunCheckpoint: runCheckpointSchema,
  RunEvent: runEventSchema,
  RunInputRequest: runInputRequestSchema,
  RunRecord: runRecordSchema,
  RunSpec: runSpecSchema,
  RunState: runStateSchema,
  ScheduleRecord: scheduleRecordSchema,
  ServerSyncChange: serverSyncChangeSchema,
  SnapshotChunk: snapshotChunkSchema,
  SnapshotChunkReceipt: snapshotChunkReceiptSchema,
  SnapshotFile: snapshotFileSchema,
  SnapshotManifest: snapshotManifestSchema,
  SnapshotUploadSession: snapshotUploadSessionSchema,
  SupportGrantRecord: supportGrantRecordSchema,
  TeamRecord: teamRecordSchema,
  TeamMemberRecord: teamMemberRecordSchema,
  TeamRole: teamRoleSchema,
  SyncApplyResult: syncApplyResultSchema,
  SyncChange: syncChangeSchema,
  SyncOperation: syncOperationSchema,
  SyncedEntity: syncedEntitySchema,
  SyncedEntityPage: syncedEntityPageSchema,
  TaskDefinition: taskDefinitionSchema,
  TerminalSessionTicket: terminalSessionTicketSchema,
  ThreadRecord: threadRecordSchema,
  ThreadMessageRun: threadMessageRunSchema,
  UpdateProjectRequest: updateProjectRequestSchema,
  UpdateThreadRequest: updateThreadRequestSchema,
  TotpRecoveryCodes: totpRecoveryCodesSchema,
  TotpSetup: totpSetupSchema,
  TotpStatus: totpStatusSchema,
  VersionResponse: versionResponseSchema,
} as const
