import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import test from 'node:test'
import { fileURLToPath } from 'node:url'

const appRoot = join(dirname(fileURLToPath(import.meta.url)), '..')
const repositoryRoot = join(appRoot, '..')

test('the Windows release smoke exercises the installed native sandbox', () => {
  const installerSmoke = readFileSync(join(appRoot, 'scripts', 'installer-crew-runtime-smoke.ps1'), 'utf8')
  const nativeSandbox = readFileSync(join(appRoot, 'src-tauri', 'src', 'native_windows_sandbox.rs'), 'utf8')
  const crewRuntime = readFileSync(join(appRoot, 'src-tauri', 'src', 'crew_python_bridge.rs'), 'utf8')
  const tauriLib = readFileSync(join(appRoot, 'src-tauri', 'src', 'lib.rs'), 'utf8')
  const releaseWorkflow = readFileSync(join(repositoryRoot, '.github', 'workflows', 'release.yml'), 'utf8')
  const candidateWorkflow = readFileSync(join(repositoryRoot, '.github', 'workflows', 'release-candidate.yml'), 'utf8')

  assert.match(nativeSandbox, /--lacowork-native-sandbox-smoke/)
  assert.match(nativeSandbox, /let repeated = setup_start\(app_data\)\?/)
  assert.match(nativeSandbox, /let current = setup_status\(app_data\);\s+if current\.ready \{\s+return Ok\(current\);/)
  assert.match(nativeSandbox, /SANDBOX_ACCOUNT\.to_ascii_lowercase\(\)/)
  assert.match(nativeSandbox, /local_principal_sid_string\(SANDBOX_GROUP, "sandbox group"\)/)
  assert.match(nativeSandbox, /icacls_sid_grant\(&sandbox_group_sid,/)
  assert.match(nativeSandbox, /grant_sandbox_runner_read_execute\(&executable\)\?/)
  assert.match(nativeSandbox, /validate_sandbox_logon\(&password\)\?/)
  assert.match(nativeSandbox, /"S-1-5-21-\{\}"/)
  assert.match(nativeSandbox, /SetEntriesInAclW/)
  assert.match(nativeSandbox, /SetNamedSecurityInfoW/)
  assert.doesNotMatch(nativeSandbox, /icacls_sid_grant\(&capability_sid,/)
  assert.match(nativeSandbox, /-NoLogo -NoProfile -NonInteractive -EncodedCommand/)
  assert.doesNotMatch(nativeSandbox, /-ExecutionPolicy Bypass -File/)
  assert.doesNotMatch(nativeSandbox, /format!\("\{\}:\(OI\)\(CI\)[A-Z]+", SANDBOX_GROUP\)/)
  assert.doesNotMatch(nativeSandbox, /SYSTEM:\(OI\)\(CI\)F/)
  assert.match(installerSmoke, /--lacowork-native-sandbox-smoke/)
  assert.match(installerSmoke, /WaitForExit\(180000\)/)
  assert.match(installerSmoke, /repeatedSetupReady -ne \$true/)
  assert.match(installerSmoke, /identityVerified -ne \$true/)
  assert.match(installerSmoke, /markerWritten -ne \$true/)
  assert.match(crewRuntime, /pub fn start_crew_runtime_bootstrap\(app: AppHandle\)/)
  assert.match(crewRuntime, /REQUIRED_EMBEDDED_PYTHON_FILES/)
  assert.match(tauriLib, /start_crew_runtime_bootstrap\(app\.handle\(\)\.clone\(\)\)/)
  assert.match(releaseWorkflow, /installer-crew-runtime-smoke\.ps1/)
  assert.doesNotMatch(releaseWorkflow, /SkipNativeSandbox/)
  assert.match(candidateWorkflow, /workflow_dispatch:/)
  assert.match(candidateWorkflow, /git merge-base --is-ancestor \$checkedOut origin\/main/)
  assert.match(candidateWorkflow, /installer-crew-runtime-smoke\.ps1/)
  assert.match(candidateWorkflow, /UninstallAfterVerification/)
  assert.doesNotMatch(candidateWorkflow, /SkipNativeSandbox/)
  assert.doesNotMatch(candidateWorkflow, /LACOWORK_NATIVE_SANDBOX_SKIP_SETUP/)
  assert.doesNotMatch(candidateWorkflow, /gh release|docker\/build-push-action|packages: write/)
})
